#server:
 # port: 8080
 # session-timeout: 30
 # tomcat.max-threads: 0
 # tomcat.uri-encoding: UTF-8

server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
    protocol-header: X-Forwarded-Proto
    remote-ip-header: X-Forwarded-For
    protocol-header-https-value: https
    max-threads: 500
    max-connections: 800
    accept-count: 500
    min-spare-threads: 250
  context-path: /
  session:
    cookie:
      path: /
    timeout: 720000


spring:
  datasource:
    url : jdbc:mysql://localhost:3306/wine?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username : root
    password : root
    driverClassName : com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  thymeleaf:
    mode: LEGACYHTML5
    cache: false
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  mapper-locations: classpath:mapping/*.xml
  typeAliasesPackage: com.ywy.domain
