common:
   configs:
    dt: 10088
    memberUrl: http://172.22.240.90:8080/cdnrCRM
    httpConnectTimeOut: 30000
    httpReadTimeOut: 30000
    httpSocketTimeOut: 30000
    httpRequestTimeOut: 50000
    httpMaxTotal: 20
    httpMaxPerRote: 20

   security:
    includeUrl: '/*,/**'
    excludeUrl: '**/*.js,**/*css,/error,/login,/register'

